import unittest
from ocr_utils import parse_score

class TestOcrUtils(unittest.TestCase):

    def test_parse_score_rejects_missing_game_points(self):
        # These are the exact formats generated by Florence-2 when it hallucinates 
        # backgrounds (like ads or arena lights) but fails to find game points.
        # This previously parsed as sets 0:0, game -1:-1 and caused the binary search to break.
        
        hallucinated_outputs = [
            "row 1: HARIMOTO, 0 row 2: HARIIMOTO, 0",
            "row 1: FELIX 0 row 2: LEBRUKE 0",
            "row 1: NSSHINBO, 0 row 2: NssHINBO, 0",
            "row 1: W, W, 0 row 2: W, 0"
        ]
        
        for text in hallucinated_outputs:
            result = parse_score(text)
            self.assertFalse(result.success, f"Expected '{text}' to fail parsing but it succeeded")
            self.assertEqual(result.error, "Incomplete score digits found")

    def test_parse_score_accepts_valid_scores(self):
        # Sanity check to ensure valid complete scores are still parsed correctly
        valid_text = "row 1: SUN YINGSHA, 2, 11 row 2: WANG MANYU, 1, 8"
        result = parse_score(valid_text)
        
        self.assertTrue(result.success)
        self.assertEqual(result.player1, "SUN YINGSHA")
        self.assertEqual(result.player2, "WANG MANYU")
        self.assertEqual(result.set1, 2)
        self.assertEqual(result.set2, 1)
        self.assertEqual(result.game1, 11)
        self.assertEqual(result.game2, 8)

    def test_parse_score_missing_row(self):
        # Missing row 2 entirely
        invalid_text = "row 1: PLAYER ONE, 0, 0"
        result = parse_score(invalid_text)
        self.assertFalse(result.success)
        self.assertIn("Could not parse rows", result.error)

if __name__ == '__main__':
    unittest.main()
