package delete_cmd

import (
	"context"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/modules/postgres"
	"github.com/testcontainers/testcontainers-go/wait"
)

const createSchemaSQL = `
CREATE TABLE IF NOT EXISTS tournaments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	name VARCHAR NOT NULL DEFAULT '',
	year SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS players (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	name VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS videos (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	youtube_id TEXT NOT NULL,
	upload_date TIMESTAMPTZ NOT NULL,
	title TEXT NOT NULL,
	day TEXT,
	processing_error TEXT
);

CREATE TABLE IF NOT EXISTS matches (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	tournament_id BIGINT NOT NULL REFERENCES tournaments(id),
	video_offset_seconds INTEGER NOT NULL DEFAULT 0,
	is_doubles BOOLEAN NOT NULL DEFAULT false,
	video_id BIGINT NOT NULL REFERENCES videos(id),
	session INTEGER
);

CREATE TABLE IF NOT EXISTS match_participants (
	match_id BIGINT NOT NULL REFERENCES matches(id),
	player_id BIGINT NOT NULL REFERENCES players(id),
	side TEXT NOT NULL,
	PRIMARY KEY (match_id, player_id, side)
);
`

func setupTestDB(t *testing.T) (*pgx.Conn, func(), string) {
	t.Helper()
	ctx := context.Background()

	pgContainer, err := postgres.Run(ctx,
		"postgres:16-alpine",
		postgres.WithDatabase("testdb"),
		postgres.WithUsername("test"),
		postgres.WithPassword("test"),
		testcontainers.WithWaitStrategy(
			wait.ForLog("database system is ready to accept connections").
				WithOccurrence(2).
				WithStartupTimeout(30*time.Second),
		),
	)
	if err != nil {
		t.Fatalf("failed to start postgres container: %v", err)
	}

	connStr, err := pgContainer.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		pgContainer.Terminate(ctx)
		t.Fatalf("failed to get connection string: %v", err)
	}

	conn, err := pgx.Connect(ctx, connStr)
	if err != nil {
		pgContainer.Terminate(ctx)
		t.Fatalf("failed to connect to test DB: %v", err)
	}

	if _, err := conn.Exec(ctx, createSchemaSQL); err != nil {
		conn.Close(ctx)
		pgContainer.Terminate(ctx)
		t.Fatalf("failed to create schema: %v", err)
	}

	cleanup := func() {
		conn.Close(ctx)
		pgContainer.Terminate(ctx)
	}

	return conn, cleanup, connStr
}

func TestDeleteTournamentData(t *testing.T) {
	conn, cleanup, connStr := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()

	// Insert test data
	var t1, t2 int
	err := conn.QueryRow(ctx, "INSERT INTO tournaments (name, year) VALUES ('Tournament A', 2026) RETURNING id").Scan(&t1)
	if err != nil {
		t.Fatalf("insert tournament failed: %v", err)
	}

	err = conn.QueryRow(ctx, "INSERT INTO tournaments (name, year) VALUES ('Tournament B', 2026) RETURNING id").Scan(&t2)
	if err != nil {
		t.Fatalf("insert tournament failed: %v", err)
	}

	var v1, v2 int
	err = conn.QueryRow(ctx, "INSERT INTO videos (youtube_id, upload_date, title) VALUES ('v1', now(), 't1') RETURNING id").Scan(&v1)
	if err != nil {
		t.Fatalf("insert video failed: %v", err)
	}
	err = conn.QueryRow(ctx, "INSERT INTO videos (youtube_id, upload_date, title) VALUES ('v2', now(), 't2') RETURNING id").Scan(&v2)
	if err != nil {
		t.Fatalf("insert video failed: %v", err)
	}

	var m1, m2 int
	err = conn.QueryRow(ctx, "INSERT INTO matches (tournament_id, video_id) VALUES ($1, $2) RETURNING id", t1, v1).Scan(&m1)
	if err != nil {
		t.Fatalf("insert match failed: %v", err)
	}
	err = conn.QueryRow(ctx, "INSERT INTO matches (tournament_id, video_id) VALUES ($1, $2) RETURNING id", t2, v2).Scan(&m2)
	if err != nil {
		t.Fatalf("insert match failed: %v", err)
	}

	var p1 int
	err = conn.QueryRow(ctx, "INSERT INTO players (name) VALUES ('Player 1') RETURNING id").Scan(&p1)
	if err != nil {
		t.Fatalf("insert player failed: %v", err)
	}

	_, err = conn.Exec(ctx, "INSERT INTO match_participants (match_id, player_id, side) VALUES ($1, $2, 'A'), ($3, $4, 'A')", m1, p1, m2, p1)
	if err != nil {
		t.Fatalf("insert participant failed: %v", err)
	}

	// Run delete func
	t.Setenv("DATABASE_URL", connStr)
	err = deleteTournamentData("Tournament A")
	if err != nil {
		t.Fatalf("delete failed: %v", err)
	}

	// Verify T1 deleted, T2 remains
	var count int
	err = conn.QueryRow(ctx, "SELECT COUNT(*) FROM tournaments WHERE id = $1", t1).Scan(&count)
	if count != 0 {
		t.Errorf("expected tournament A to be deleted")
	}

	err = conn.QueryRow(ctx, "SELECT COUNT(*) FROM tournaments WHERE id = $1", t2).Scan(&count)
	if count != 1 {
		t.Errorf("expected tournament B to remain")
	}

	err = conn.QueryRow(ctx, "SELECT COUNT(*) FROM videos WHERE id = $1", v1).Scan(&count)
	if count != 0 {
		t.Errorf("expected video 1 to be deleted")
	}

	err = conn.QueryRow(ctx, "SELECT COUNT(*) FROM videos WHERE id = $1", v2).Scan(&count)
	if count != 1 {
		t.Errorf("expected video 2 to remain")
	}

	err = conn.QueryRow(ctx, "SELECT COUNT(*) FROM matches WHERE id = $1", m1).Scan(&count)
	if count != 0 {
		t.Errorf("expected match 1 to be deleted")
	}

	err = conn.QueryRow(ctx, "SELECT COUNT(*) FROM matches WHERE id = $1", m2).Scan(&count)
	if count != 1 {
		t.Errorf("expected match 2 to remain")
	}

	err = conn.QueryRow(ctx, "SELECT COUNT(*) FROM match_participants WHERE match_id = $1", m1).Scan(&count)
	if count != 0 {
		t.Errorf("expected participant 1 to be deleted")
	}
}
