FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    xz-utils \
    zip \
    libglu1-mesa \
    libgtk-3-dev \
    pkg-config \
    clang \
    cmake \
    ninja-build \
    libmpv-dev \
    mpv \
    weston \
    xwayland \
    dbus-x11 \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/flutter/flutter.git -b stable /flutter
ENV PATH="/flutter/bin:${PATH}"

RUN flutter config --enable-linux-desktop

