# Ignore everything
**

# Except what we explicitly need
!florence_extractor/
florence_extractor/cropped_images/
florence_extractor/__pycache__/
florence_extractor/venv/
florence_extractor/.git/
florence_extractor/testdata/
florence_extractor/test_data_sample.csv
florence_extractor/training.log

# OpenVINO does not need the massive PyTorch weights
florence_extractor/florence2-tt-finetuned/*.safetensors
florence_extractor/florence2-tt-finetuned/*.bin
